name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs_on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Good -Bye"
