name: five-workflow
on: push
env:
  DB_USERNAME: karthik
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
      - name: build-step2
        run: echo "{{ env.DB_USERNAME }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "step2"
