name: third workflow
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: start the job
      run: echo "starting the job"
